title: Jesse Trimble
email: jesseltrimble@gmail.com
description: >
  Professional Rubyist and functional programming enthusiast, building the web from Boulder CO.
baseurl: ""
url: "http://jessetrimble.net"
twitter_username: jessetrimble
github_username:  jtrim
excerpt_separator: <!--\-->
markdown: kramdown
kramdown:
  use_coderay: true
  auto_ids: true
  hard_wrap: false
  input: GFM
  smart_quotes:  ["apos", "apos", "quot", "quot"]
  coderay_line_numbers: nil
